### ISSUE TITLE
Lots of nodes listed as serving Graphene, which don't when connected with BUCash client.

### ISSUE THREAD

**Issue by Justaphf** [BitcoinUnlimited/cashnodes-frontend#28]
With the graphene service bit now turned on, it looks like the cashnodes.io site is showing way more nodes as offering NODE_GRAPHENE services than actually are when connected via a BUCash client (with graphene enabled via the `bitcoin.conf` file of course).

Compared the first 5 or 6 in the list that would connect with my node by using `addnode` cli.  When displaying the services offered in the debug window (Qt client) none of them were serving graphene.  Out of 28 BUCash1.3.0.1 nodes connected to me, only 1 has graphene turned on and that wasn't one I connected to via `addnode`

**Comment by Justaphf** [comment]
And I just had a DUH moment...looked into the service bits in the BUCash client code...the bit at 32 (1 << 5) is for NODE_CASH, NODE_GRAPHENE is 64 (1 << 6).

Will put in a PR to correct.

**Comment by sickpig** [comment]
fixed by #27, thanks @Justaphf 
closing
