### ISSUE TITLE
Auto-detect new clients for pie-chart breakdown list

### ISSUE THREAD

**Issue by AndrewClifford** [BitcoinUnlimited/cashnodes-frontend#33]
I propose an enhancement where this list is generated from the data.  
Extract from text e.g. "XT" from /Bitcoin XT: possibly by removing just the word "Bitcoin" and spaces.
If the count is >1% then show slices, else collate as "others".
At present it appears to be hard-coded:
ABC
Bitcoin Unlimited
Others
XT

**Comment by sickpig** [comment]
Agreed, although as a temporary stop-gap solution I will add Bitcoin SV and Bitprim to the hardcoded list. Will work an a proper solution tomorrow.

**Comment by sickpig** [comment]
fixed for the `develop` branch n commit 4fda6af8fcd
